export const projects = [
  {
    title: 'Graph Learning Internship, Société Générale',
    description: "Implementation of a graph learning solution to document the data catalog of the société générale. Implementation of GSage, GCN and GAT architectures on Pytorch. Data Engineering tasks : Java, Spark, Kubernetes, Airflow, Hadoop, Jenkins, Hue. Presentation of my work in the teams group of the Société Générale (110 people) ",
      image: '/images/7.png',
      tags: ['Graph Learning', 'Big Data', 'Airflow', 'Pytorch', '6 months'],
    source: 'https://google.com',
    visit: 'https://google.com',
    information:'Data Science',
    id: 0,
  },
  {
    title: 'Incoming personal project',
    description:"Implementing my own project web application, related to Data Science with machine learning algorithms and use of public API. Stay condifential becasue of the fact that you'll find on your phone store soon :)   ",
    image: '/images/11.png',
    tags: ['Web application', 'APIs', 'Python', 'Mathematics', 'Social'],
    source: 'https://github.com/Run-Light/Run-Light',
    visit: 'https://github.com/Run-Light/Run-Light',
    information:'Software Engineer',
    id: 1,
  },
  {
    title: 'Prediction of ground reaction thanks to wearable sensors',
    description:"Research problem, the stance force platforms are too expensive for runner who wants to know their stats. Regression problem, metrics at 94% accuracy, low loss function, research project. EPF Fundation    ",
    image: '/images/8.png',
    tags: ['Medecine', 'LightGBM Regressor', 'Python', '3 months'],
    source: 'https://github.com/Run-Light/Run-Light',
    visit: 'https://github.com/Run-Light/Run-Light',
    information:'Data Science',
    id: 1,
  },
  {
    title: 'Administration website using Django in Backend / React in Frontend',
    description:"Followed a youtube video to deepen my knowledge in React and Django. Use of axios, react_framework, CSS",
    image: '/images/6.png',
    tags: ['React', ' Django', 'Python'],
    source: 'https://github.com/Run-Light/Run-Light',
    visit: 'https://github.com/Run-Light/Run-Light',
    information:'Full Stack',
    id: 1,
  },
  {
    title: 'CEA Software Engineer task ',
    description: "Delivered a solution on operators’s needs (nuclear fuel manufacturing form). Implementation of a ceramic manufacturing database to cross-reference operating conditions",
      image: '/images/9.png',
      tags: ['JavaScript', 'Excel', 'VBA', '6 months'],
    source: 'https://google.com',
    visit: 'https://google.com',
    information:'Software Engineer',
    id: 2,
  },
  {
    title: 'Skin cancer detection ',
    description: "This is a code repository for the corresponding personal project on predicting skin cancer (multi classification).",
    image: '/images/10.png',
    tags: ['Neural Network', 'ConvNet', 'Data Processing'],
    source: 'https://google.com',
    visit: 'https://google.com',
    information:'Data Science',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Engineering school, EPF', },
  { year: 2020, text: 'Degree in mathematics, Aix Marseille Univ', },
  { year: 2021, text: 'First Internship as Software Engineer, CEA nuclear field', },
  { year: 2022, text: 'Specialization in Data Science', },
  { year: 2023, text: 'Last Internship as Data Scientist on Graph Learning at Société Générale', },
  
];